-- 1. Enable UUID extension (Standard for Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- TABLE 1: GUEST TRACKING (The "5 Free Prompts")
-- Identifies devices via FingerprintJS
-- ==========================================
CREATE TABLE IF NOT EXISTS public.guest_tracking (
    fingerprint_id TEXT PRIMARY KEY, -- The ID from FingerprintJS
    prompt_count INTEGER DEFAULT 0,
    last_ip TEXT,                    -- To cross-reference with abuse monitor
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- TABLE 2: USER STATS (The "Logged In" Limits)
-- Links to Supabase Auth (auth.users)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.user_stats (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    prompt_count INTEGER DEFAULT 0,
    is_premium BOOLEAN DEFAULT FALSE, -- For future scalability
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- TABLE 3: IP ABUSE MONITOR (The "Shield")
-- Tracks aggressive usage from specific networks
-- ==========================================
CREATE TABLE IF NOT EXISTS public.ip_abuse_monitor (
    ip_address TEXT PRIMARY KEY,
    request_count_1h INTEGER DEFAULT 0, -- Resets every hour (via logic or cron)
    last_request_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_blocked BOOLEAN DEFAULT FALSE
);

-- ==========================================
-- TABLE 4: CHAT SESSIONS (The "Context Container")
-- Groups messages together. Handles the "Guest -> User" merge.
-- ==========================================
CREATE TABLE IF NOT EXISTS public.chat_sessions (
    session_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    fingerprint_id TEXT, -- Initially linked to device
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Linked after login
    title TEXT, -- Optional: "Chat about Python..."
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast lookups when merging sessions
CREATE INDEX IF NOT EXISTS idx_sessions_fingerprint ON public.chat_sessions(fingerprint_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON public.chat_sessions(user_id);

-- ==========================================
-- TABLE 5: CHAT MESSAGES (The "History")
-- Stores the actual conversation for LangChain memory
-- ==========================================
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.chat_sessions(session_id) ON DELETE CASCADE,
    role TEXT CHECK (role IN ('user', 'ai', 'system')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for retrieving history quickly
CREATE INDEX IF NOT EXISTS idx_messages_session ON public.chat_messages(session_id);

-- ==========================================
-- AUTOMATION: HANDLE "UPDATED_AT" TIMESTAMP
-- Automatically updates the timestamp when a row changes
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply the trigger to tracking tables (DROP/CREATE to avoid errors if exists)
DROP TRIGGER IF EXISTS update_guest_time ON public.guest_tracking;
CREATE TRIGGER update_guest_time BEFORE UPDATE ON public.guest_tracking
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_user_time ON public.user_stats;
CREATE TRIGGER update_user_time BEFORE UPDATE ON public.user_stats
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_session_time ON public.chat_sessions;
CREATE TRIGGER update_session_time BEFORE UPDATE ON public.chat_sessions
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Permission Policies (RLS)
ALTER TABLE guest_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
