import React from 'react';
import { Link } from 'react-router-dom';

export default function Disclaimer() {
  return (
    <div className="h-[100dvh] w-full flex flex-col p-4 md:p-6 bg-gradient-to-br from-indigo-50 via-white to-violet-50 dark:from-[#0F1016] dark:via-[#151621] dark:to-[#1E1F2E] font-sans relative overflow-y-auto">
      
      {/* Decorative Background Elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none fixed">
          <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-indigo-500/10 rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-violet-500/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
      </div>

      <div className="relative w-full max-w-3xl bg-white/80 dark:bg-[#1E1F2E]/90 backdrop-blur-2xl p-8 md:p-12 rounded-3xl shadow-2xl border border-white/50 dark:border-white/10 ring-1 ring-black/5 dark:ring-white/5 m-auto">
        
        <div className="flex flex-col items-center text-center mb-10">
            <div className="w-16 h-16 bg-red-50 dark:bg-red-500/20 text-red-500 rounded-2xl flex items-center justify-center mb-6 shadow-sm">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
            </div>
            <h1 className="text-3xl md:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-violet-500 dark:from-white dark:to-slate-300 tracking-tight">
            Medical Disclaimer
            </h1>
            <div className="h-1 w-20 bg-gradient-to-r from-indigo-500 to-violet-500 rounded-full mt-6"></div>
        </div>
        
        <div className="space-y-6 text-slate-600 dark:text-slate-300 leading-relaxed text-lg text-justify md:text-left font-medium opacity-90">
          <p className="first-letter:text-4xl first-letter:font-bold first-letter:text-indigo-500 first-letter:float-left first-letter:mr-2 leading-relaxed">
            The information provided by this AI is intended for home-based, general informational purposes only. It is not medical advice and should not be used as a substitute for professional medical advice, diagnosis, or treatment from a licensed physician or qualified healthcare provider.
          </p>
          
          <p>
            The content generated by this AI is derived from a combination of publicly available information, general knowledge, and multiple sources, which may include both verified and unverified materials. As such, the accuracy, completeness, and reliability of the information cannot be guaranteed.
          </p>
          
          <p>
            Users should exercise their own judgment and are strongly advised to consult a qualified medical professional before making any health-related decisions. Do not ignore, delay, or discontinue professional medical advice based on information obtained from this AI.
          </p>
          
          <div className="bg-slate-50 dark:bg-black/20 p-6 rounded-xl border border-slate-100 dark:border-white/5 text-sm md:text-base text-slate-500 dark:text-slate-400 italic">
            By using this service, you acknowledge that the information is provided “as is”, and the creators, owners, and operators of this AI disclaim all liability for any direct or indirect loss, harm, or damages arising from the use or reliance on the information provided.
          </div>
        </div>

        <div className="mt-12 flex justify-center">
          <Link 
            to="/" 
            className="group relative inline-flex items-center justify-center px-8 py-4 text-lg font-bold text-white transition-all duration-300 bg-gradient-to-r from-indigo-600 to-violet-600 rounded-2xl shadow-lg hover:shadow-indigo-500/30 hover:-translate-y-1 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 overflow-hidden"
          >
            <span className="relative z-10 flex items-center gap-2">
                I Understand, Continue Chat
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 transform transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6" />
                </svg>
            </span>
            <div className="absolute inset-0 bg-gradient-to-r from-violet-600 to-indigo-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          </Link>
        </div>
      </div>
    </div>
  );
}
